name: Update Checker hanwckf

env:
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x
  REPO_BRANCH: openwrt-21.02

on:
  workflow_dispatch:
#  schedule:
#  - cron: 0 14 * * 2,4,6

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
         git log --name-only >> text.txt
         echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3
      with:
         path: .commitHash
         key: HEAD-hanwckf-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
         echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
        
    - name: Email notification
      uses: dawidd6/action-send-mail@master
      if: steps.cacheHash.outputs.cache-hit != 'true' && !cancelled()
      with:
         server_address: smtp.163.com
         server_port: 465
         username: ${{ secrets.MAILUSERNAME }}
         password: ${{ secrets.MAILPASSWORD }}
         subject: hanwckf update source code
         body: file://text.txt
         to: ${{ secrets.MAIL }}
         from: GitHub Actions For Checking Update
         content_type: text/html
         
#    - name: Trigger build
#      if: steps.cacheHash.outputs.cache-hit != 'true'
#      uses: peter-evans/repository-dispatch@v1
#      with:
#         token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
#         event-type: Source Code Update

    - name: Delete workflow runs
      uses: FunctionXJB/delete-workflow-runs@main
      with:
         retain_days: 1
         keep_minimum_runs: 2
